"""empty message

Revision ID: a49406c7651f
Revises: 64afb8097042
Create Date: 2024-05-07 01:02:19.617074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a49406c7651f'
down_revision = '64afb8097042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_value',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=100), nullable=False),
    sa.Column('f1', sa.Float(), nullable=False),
    sa.Column('f2', sa.Float(), nullable=False),
    sa.Column('f3', sa.Float(), nullable=False),
    sa.Column('f4', sa.Float(), nullable=False),
    sa.Column('f5', sa.Float(), nullable=False),
    sa.Column('f6', sa.Float(), nullable=False),
    sa.Column('f7', sa.Float(), nullable=False),
    sa.Column('f8', sa.Float(), nullable=False),
    sa.Column('f9', sa.Float(), nullable=False),
    sa.Column('f10', sa.Float(), nullable=False),
    sa.Column('f11', sa.Float(), nullable=False),
    sa.Column('f12', sa.Float(), nullable=False),
    sa.Column('f13', sa.Float(), nullable=False),
    sa.Column('f14', sa.Float(), nullable=False),
    sa.Column('f15', sa.Float(), nullable=False),
    sa.Column('f16', sa.Float(), nullable=False),
    sa.Column('f17', sa.Float(), nullable=False),
    sa.Column('f18', sa.Float(), nullable=False),
    sa.Column('f19', sa.Float(), nullable=False),
    sa.Column('f20', sa.Float(), nullable=False),
    sa.Column('f21', sa.Float(), nullable=False),
    sa.Column('f22', sa.Float(), nullable=False),
    sa.Column('f23', sa.Float(), nullable=False),
    sa.Column('f24', sa.Float(), nullable=False),
    sa.Column('f25', sa.Float(), nullable=False),
    sa.Column('f26', sa.Float(), nullable=False),
    sa.Column('f27', sa.Float(), nullable=False),
    sa.Column('f28', sa.Float(), nullable=False),
    sa.Column('f29', sa.Float(), nullable=False),
    sa.Column('f30', sa.Float(), nullable=False),
    sa.Column('f31', sa.Float(), nullable=False),
    sa.Column('f32', sa.Float(), nullable=False),
    sa.Column('f33', sa.Float(), nullable=False),
    sa.Column('f34', sa.Float(), nullable=False),
    sa.Column('f35', sa.Float(), nullable=False),
    sa.Column('f36', sa.Float(), nullable=False),
    sa.Column('f37', sa.Float(), nullable=False),
    sa.Column('f38', sa.Float(), nullable=False),
    sa.Column('f39', sa.Float(), nullable=False),
    sa.Column('f40', sa.Float(), nullable=False),
    sa.Column('f41', sa.Float(), nullable=False),
    sa.Column('f42', sa.Float(), nullable=False),
    sa.Column('f43', sa.Float(), nullable=False),
    sa.Column('f44', sa.Float(), nullable=False),
    sa.Column('f45', sa.Float(), nullable=False),
    sa.Column('f46', sa.Float(), nullable=False),
    sa.Column('f47', sa.Float(), nullable=False),
    sa.Column('f48', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mark_value',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('m1', sa.Float(), nullable=False),
    sa.Column('m2', sa.Float(), nullable=False),
    sa.Column('m3', sa.Float(), nullable=False),
    sa.Column('m4', sa.Float(), nullable=False),
    sa.Column('m5', sa.Float(), nullable=False),
    sa.Column('m6', sa.Float(), nullable=False),
    sa.Column('m7', sa.Float(), nullable=False),
    sa.Column('m8', sa.Float(), nullable=False),
    sa.Column('m9', sa.Float(), nullable=False),
    sa.Column('m10', sa.Float(), nullable=False),
    sa.Column('m11', sa.Float(), nullable=False),
    sa.Column('m12', sa.Float(), nullable=False),
    sa.Column('m13', sa.Float(), nullable=False),
    sa.Column('m14', sa.Float(), nullable=False),
    sa.Column('m15', sa.Float(), nullable=False),
    sa.Column('m16', sa.Float(), nullable=False),
    sa.Column('m17', sa.Float(), nullable=False),
    sa.Column('m18', sa.Float(), nullable=False),
    sa.Column('m19', sa.Float(), nullable=False),
    sa.Column('m20', sa.Float(), nullable=False),
    sa.Column('m21', sa.Float(), nullable=False),
    sa.Column('m22', sa.Float(), nullable=False),
    sa.Column('m23', sa.Float(), nullable=False),
    sa.Column('m24', sa.Float(), nullable=False),
    sa.Column('m25', sa.Float(), nullable=False),
    sa.Column('m26', sa.Float(), nullable=False),
    sa.Column('m27', sa.Float(), nullable=False),
    sa.Column('m28', sa.Float(), nullable=False),
    sa.Column('m29', sa.Float(), nullable=False),
    sa.Column('m30', sa.Float(), nullable=False),
    sa.Column('m31', sa.Float(), nullable=False),
    sa.Column('m32', sa.Float(), nullable=False),
    sa.Column('m33', sa.Float(), nullable=False),
    sa.Column('m34', sa.Float(), nullable=False),
    sa.Column('m35', sa.Float(), nullable=False),
    sa.Column('m36', sa.Float(), nullable=False),
    sa.Column('m37', sa.Float(), nullable=False),
    sa.Column('m38', sa.Float(), nullable=False),
    sa.Column('m39', sa.Float(), nullable=False),
    sa.Column('m40', sa.Float(), nullable=False),
    sa.Column('m41', sa.Float(), nullable=False),
    sa.Column('m42', sa.Float(), nullable=False),
    sa.Column('m43', sa.Float(), nullable=False),
    sa.Column('m44', sa.Float(), nullable=False),
    sa.Column('m45', sa.Float(), nullable=False),
    sa.Column('m46', sa.Float(), nullable=False),
    sa.Column('m47', sa.Float(), nullable=False),
    sa.Column('m48', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('predict_result', sa.Integer(), nullable=False),
    sa.Column('decision_path', sa.Text(), nullable=False),
    sa.Column('evaluate_result', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('mark_value')
    op.drop_table('feature_value')
    # ### end Alembic commands ###
